### ISSUE TITLE
Text attribute in model DBItem is empty in post_save signal

### ISSUE THREAD

**Issue by luismojena** [kyokenn/djradicale#10]
I have installed djradicale==0.0.13 and django==1.11.1.
I want to connect to a post_save signal of the model DBItem, so when the text attribute is updated or a new object is created I can update other model with the information of the event. The problem is that the text attribute in the signal is empty, here is an example of my code:

```
@receiver(post_save, sender=DBItem)
def create_ocurrence(sender, instance, created, raw, *args, **kwargs):
    if created:  
        print('------------------------------------------------------------------------------')
        print(instance.text)
        print(raw)
        print('------------------------------------------------------------------------------')
```

And that prints:

>         ------------------------------------------------------------------------------
>         
>         True
>         ------------------------------------------------------------------------------

Any thoughts?

**Comment by kyokenn** [comment]
Yes. This is expected. DBItem's are created with empty text attribute, text attribute actually updates later.

**Comment by luismojena** [comment]
Thanks, I manage to work around that behaviour. Great library BTW
