### ISSUE TITLE
Why Django 2.0 only?

### ISSUE THREAD

**Issue by anx-ckreuzberger** [kyokenn/djradicale#15]
Is there a reason why this project is limited to Django 2.0?

https://github.com/kyokenn/djradicale/blob/3ea2f3bf738eb58d5e9862bbb8ccdaeb49336005/setup.py#L41

I tested it with Django Python 3 + Django 1.11 and it works just fine.

The reason why I am asking is: Django 1.11 is the current LTS Version of Django, and therefor the project I am working on is sticking with Django 1.11 and not going to upgrade to Django 2+ (until the next Django LTS, Version 2.2, is released).

If you want, I can create a Pull Request.

**Comment by kyokenn** [comment]
Ok. If it works fine you can make a PR.

**Comment by kyokenn** [comment]
Ported to django 4.0.
