### ISSUE TITLE
last Python2 support

### ISSUE THREAD

**Issue by Hinnack** [kyokenn/djradicale#16]
Hi,
what was the last python2 version?

using the master branch on Python 2.7.9 I die in the first place by 
from io import StringIO as StringIO
as it does not support unicode

when using:
from StringIO import StringIO as StringIO

I die in loading auth by saying:
contrib.auth is not a module...

regards,
Hinnack

**Comment by kyokenn** [comment]
Python2 was never supported.
Python2 is dead. Django has already dropped a Python2 support.

**Comment by Hinnack** [comment]
thanks for your replay.
it works for me. I only renamed every django.py to something else and fixed the StringIO problem.
