### ISSUE TITLE
Event / collection/ calendar not persisted

### ISSUE THREAD

**Issue by bitbeamer** [kyokenn/djradicale#17]
I am using djradciale from master. Django is running and I can subscribe to a new calendar (a collection is created).
However, on put no event data is persisted. It just stores an object of type djradicale.Collections.
After lots of debugging, I am still not sure I understand where the actual event data is supposed to be stored.

Server prints a 201 message, but all I get in the DB is the Collection object. No events.
PUT response status for 'test/Calendar2.ics' in 125.581 seconds: 201 Created

I am using Thunderbird as calendar client.

**Comment by kyokenn** [comment]
The events are stored in DBItem model, single DBItem object per each event. I'm using Thunderbird too and it always worked fine.

**Comment by bitbeamer** [comment]
Thanks kyokenn for looking at this issue. Let me try that again and get back with steps to reproduce (if I can reproduce it)

**Comment by bitbeamer** [comment]
Gave it another try:
- checked out djradicale
- created a simple project and installed the local djradicale module
- updated all relevant files as in the test project in git

Server starts fine but whatever URL I'm trying in Thunderbird, I am getting "access defined by rights backend". 
In Thunderbird I tried:
- http://localhost:8000/
- http://localhost:8000/radicale/
- http://localhost:8000/radicale/test
- http://localhost:8000/radicale/test/
- http://localhost:8000/radicale/test/newcal
- http://localhost:8000/radicale/test/newcal/
- http://localhost:8000/radicale/test/newcal.ics
- http://localhost:8000/radicale/test/newcal.ics/

(test being the name of the Django superuser)

So my question I guess is more, what URL should I put in in Thunderbird so that a new calendar gets created?

Here is the log for URL 

  Base prefix (from HTTP_X_SCRIPT_NAME): '/radicale'
  Sanitized path: '/'
  Access to '/' denied for anonymous user
  Asking client for authentication
  Response content:
  Access to the requested resource forbidden.
  PROPFIND response status for '' with depth '0' in 0.002 seconds: 401 Unauthorized
  Unauthorized: /radicale/
  [05/Feb/2023 07:38:07] "PROPFIND /radicale/ HTTP/1.1" 401 61
  auth type is 'djradicale.auth'
  storage type is 'djradicale.storage'
  rights type is 'djradicale.rights'
  web type is 'radicale.web.internal'
  PROPFIND request for '' with depth '0' received from 127.0.0.1 using 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) Gecko/20100101 Thunderbird/102.6.1'
  Request headers:
  {'CLICOLOR': '1',
  'COMMAND_MODE': 'unix2003',
  'CONTENT_LENGTH': '203',
  'CONTENT_TYPE': 'text/xml; charset=utf-8',
  'DJANGO_SETTINGS_MODULE': 'mysite.settings',
  'GATEWAY_INTERFACE': 'CGI/1.1',
  'HOME': '/Users/christian',
  'HOMEBREW_CELLAR': '/opt/homebrew/Cellar',
  'HOMEBREW_PREFIX': '/opt/homebrew',
  'HOMEBREW_REPOSITORY': '/opt/homebrew',
  'HTTP_ACCEPT': 'text/xml',
  'HTTP_ACCEPT_CHARSET': 'utf-8,*;q=0.1',
  'HTTP_ACCEPT_ENCODING': 'gzip, deflate, br',
  'HTTP_ACCEPT_LANGUAGE': 'en-GB,en;q=0.5',
  'HTTP_AUTHORIZATION': 'Basic **masked**',
  'HTTP_CACHE_CONTROL': 'no-cache',
  'HTTP_CONNECTION': 'keep-alive',
  'HTTP_DEPTH': '0',
  'HTTP_HOST': 'localhost:8000',
  'HTTP_ORIGIN': 'http://localhost:8000',
  'HTTP_PRAGMA': 'no-cache',
  'HTTP_SEC_FETCH_DEST': 'empty',
  'HTTP_SEC_FETCH_MODE': 'no-cors',
  'HTTP_SEC_FETCH_SITE': 'same-origin',
  'HTTP_USER_AGENT': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:102.0) '
      'Gecko/20100101 Thunderbird/102.6.1',
  'HTTP_X_SCRIPT_NAME': '/radicale',
  'IDE_PROJECT_ROOTS': '/Users/christian/Documents/projects/dj',
  'INFOPATH': '/opt/homebrew/share/info:',
  'IPYTHONENABLE': 'True',
  'JAVA_HOME': '/Users/christian/projects/jdk-18.0.2.jdk/Contents/Home',
  'LC_CTYPE': 'en_US.UTF-8',
  'LOGNAME': 'christian',
  'LaunchInstanceID': '0F8C71A7-F3F0-4B24-AC9E-193F62338558',
  'MANPATH': '/opt/homebrew/share/man::',
  'OLDPWD': '/',
  'PATH_INFO': '',
  'PS1': '(.venv) ',
  'PWD': '/Users/christian/Documents/projects/dj',
  'PYCHARM_DISPLAY_PORT': '63342',
  'PYCHARM_HOSTED': '1',
  'PYDEVD_LOAD_VALUES_ASYNC': 'True',
  'PYTHONIOENCODING': 'UTF-8',
  'PYTHONUNBUFFERED': '1',
  'QUERY_STRING': '',
  'REMOTE_ADDR': '127.0.0.1',
  'REMOTE_HOST': '',
  'REQUEST_METHOD': 'PROPFIND',
  'RUN_MAIN': 'true',
  'SCRIPT_NAME': '',
  'SECURITYSESSIONID': '186a6',
  'SERVER_NAME': '1.0.0.127.in-addr.arpa',
  'SERVER_PORT': '8000',
  'SERVER_PROTOCOL': 'HTTP/1.1',
  'SERVER_SOFTWARE': 'WSGIServer/0.2',
  'SHELL': '/bin/zsh',
  'SSH_AUTH_SOCK': '/private/tmp/com.apple.launchd.7CqbAU0LAZ/Listeners',
  'TERM': 'xterm-256color',
  'TMPDIR': '/var/folders/g5/mwyn5h75761blg13kndg09hw0000gn/T/',
  'TZ': 'UTC',
  'USER': 'christian',
  'VIRTUAL_ENV': '/Users/christian/Documents/projects/dj/.venv',
  'XPC_FLAGS': '0x0',
  'XPC_SERVICE_NAME': 'application.com.jetbrains.pycharm.40727202.42097494',
  '__CFBundleIdentifier': 'com.jetbrains.pycharm',
  '__CF_USER_TEXT_ENCODING': '0x1F5:0x0:0x0',
  'wsgi.errors': <_io.TextIOWrapper name='<stderr>' mode='w' encoding='utf-8'>,
  'wsgi.file_wrapper': <class 'wsgiref.util.FileWrapper'>,
  'wsgi.input': <django.core.handlers.wsgi.LimitedStream object at 0x103d06920>,
  'wsgi.multiprocess': False,
  'wsgi.multithread': True,
  'wsgi.run_once': False,
  'wsgi.url_scheme': 'http',
  'wsgi.version': (1, 0)}
  Base prefix (from HTTP_X_SCRIPT_NAME): '/radicale'
  Sanitized path: '/'
  ---> authorization  /
  Successful login: 'test'
  ---> authorization test /test/
  Access to principal path '/test/' denied by rights backend
