### ISSUE TITLE
Release tags?

### ISSUE THREAD

**Issue by fladi** [kyokenn/djradicale#18]
It would be nice to have tags corresponding to each release in git. Would it be possible to tags each released commit and push those tags to github? Background is that I'm using djradicale in one of my projects and I'd like to package it for the Debian repository.

**Comment by kyokenn** [comment]
Would it be enough to push the current tag only? Older versions/commits are outdated.

**Comment by fladi** [comment]
Sure, it would at least help for my use-case. Thanks!

**Comment by kyokenn** [comment]
I have pushed the tag.

**Comment by fladi** [comment]
Thanks!
