### ISSUE TITLE
Synchronization issue.

### ISSUE THREAD

**Issue by z4nD4R** [kyokenn/djradicale#2]
Hello,

based on couple of my testing I have observed a weird (or I'm missing smth) behavior in synchronization.
During the test I've been using 4 client (including my own app):
- My own app
- Lightning calendar
- Evolution default calendar 
- DAVdroid

Described behavior can be observed across the all clients. 
# Results of the test:

_from Lightning:_
- adding, editing, removing the task work like charm -> task are added into other clients and of course I 
  can see them into Django Admin Page

_from DAVdroid:_
- the same as from Lightning all working

_from Evolutions:_
- the same working scenario.

_from my own app:_
- here actually starts the trouble starts
- If I add DBItem, via DBCollection, I can see this item properly in Django Admin Page, but it is not reflected to any CALDAV client neither to Lightning, DAVdroid or Evolution.
- No matter how log I will be wait for synchronization/turn it on/of or try to manual synchronization
- New task will be only add if I add another one from client. Than the one I have added appears on clients, but I can see it twice in Django Admin Page.

I don't know if I'm missing smth, or this kind of behavior is expected. 
Thank you for any advice.

**Comment by kyokenn** [comment]
Is your App server-side? How do you adding DBItem? With a django ORM or raw SQL?
When you updating your collection make sure you also updating the "Last modified field". This field is used in sync process.
