### ISSUE TITLE
Add a tag

### ISSUE THREAD

**Issue by mir06** [kyokenn/djradicale#20]
Dear @kyokenn, would you mind to make a new tag and upload it to pypi.org. Thanks!

**Comment by mir06** [comment]
Any chance you are uploading a new version to pypi? Or do you prefer a fork and publication under a different name. Please let me know. Thanks.

**Comment by kyokenn** [comment]
Looks like I lost access to my pypi account and can't update or delete package. It could take a long time to recover my account, so you can upload the package undef different name.

**Comment by mir06** [comment]
I just did that as [django-radicale](https://pypi.org/project/django-radicale/).
