### ISSUE TITLE
Resposne code 403

### ISSUE THREAD

**Issue by cs-stainly** [kyokenn/djradicale#3]
Hello,

I set up my server as the sample project suggests.
But all I get is a 403 (forbidden) response.
When prompted, I entered the credentials of my django admin account.

Any idea what I am doing wrong?

**Comment by cs-stainly** [comment]
I downloaded the test project and tried to use that. Same issue.

**Comment by cs-stainly** [comment]
I figured out that djradicale doesn't like the i18n patterns of django.

**Comment by Jonny0815** [comment]
did you fix it? got the same problem, any advice ?

**Comment by cs-stainly** [comment]
No. We decided to stop the project we needed this for.
Sorry to disappoint.

Edit: On a second thought, I believe we just disabled the i18n patterns in the urls.py
But that’s more of a workaround
