### ISSUE TITLE
Disappearing Events

### ISSUE THREAD

**Issue by cs-stainly** [kyokenn/djradicale#6]
When I create multiple events one by one with Evolution, then I observe a odd behavior.

1.) I created "Event 1" starting at 1pm, ending at 1.30pm.
2.) Then I created "Event 2" starting at 2pm, ending at 2.30pm.
3.) When I created "Event 3" starting at 3pm, ending at 3.30pm, then it disappeared after a few seconds and Evolution stated that the event was deleted and that I might want to close the editor.
4.) I tried it again two times with no success. 
5.) I waited a moment and tried it a third time. This time it was created.
6.) I created a fourth event "Event 4" starting at 4pm, ending at 4.30pm. That worked without a problem.

I was able to synchronize with an iPhone and the iPhone and Evolution are able to change the events.
However, the disappearing events annoy me. They do show up in the database but none of the clients gets them when they try to synchronize. The names of all [6] events look similar:
`20160719T123152Z-4626-1000-4625-131_Loki-20160719T123155Z.ics`
`20160719T123158Z-4626-1000-4625-141_Loki-20160719T123201Z.ics`
`20160719T123205Z-4626-1000-4625-151_Loki-20160719T123209Z.ics`
`20160719T123224Z-4626-1000-4625-161_Loki-20160719T123230Z.ics`
`20160719T123259Z-4626-1000-4625-171_Loki-20160719T123305Z.ics`
`20160719T123320Z-4626-1000-4625-181_Loki-20160719T123326Z.ics`

Is that an issue with my server being not fast enough to handle the requests?

**Comment by cs-stainly** [comment]
One sidenote: The text field of the DBItem is incredibly long. I am not sure it is supposed to be that long (about 5000 lines). I believe that the serialization is not working properly.

I attached a file with the content of one DBItem "Text" field.
[DBItem-text.txt](https://github.com/okami-1/djradicale/files/371677/DBItem-text.txt)

**Comment by kyokenn** [comment]
So you lost 2 events?

The PUT requests from the Evolution are long. There is a lot of data about timezone. The other clients are creating smaller events.

**Comment by cs-stainly** [comment]
Yes, I lost two events. There are 6 in the database but only 4 are visible on either client.

I also lost a few when I was changing some events randomly (and quite rapidly at some time)

**Comment by kyokenn** [comment]
This should be fixed for now. But you have to manually delete the broken events from the database.
