### ISSUE TITLE
DJRadicale for starters

### ISSUE THREAD

**Issue by Ethan920713** [kyokenn/djradicale#9]
I've been working with Radicale for a while. I installed it on my computer and started a server, and I was able to create events and synchronize from my phone (using DAVDroid) and my laptop (using Thunderbird and Lighthing). 

I'd like to know how can I use this djradicale, I saw the test_project and I downloaded it. I started it on Pycharm and ran the server using python manage.py runserver. In my web browser I saw the admin and some other URL called 'pim' which asked me for an user and a password. What I am supposed to do here? How can I use djradicale? Thanks in advance.

**Comment by kyokenn** [comment]
DjRadicale is a Django App. So you need a basic knowledge of using a Django Framework.
DjRadicale is an App for integrating Radicale server inside the Django-based project (website or API server).

DjRadicale is a wrapper around the Radicale with Django ORM as a storage backend. So, it can be used the same way as the Radicale with DAVDroid, Lighthing or any other CardDAV/CalDAV client.

test_project is a minimal simple example of usage an app. The user registration page is not included in the test_project. You have to create a user by yourself. The first user in any Django project can be created with:
$ manage.py createsuperuser

**Comment by Ethan920713** [comment]
Thanks for your replay

Interesting, I created a new superuser and I accessed the admin page. 

According to you I can use djradicale the same way as Radicale, how so? For example with radicale I start the server using my configurations (in the config file) and I can check on the url the server is running, also connect and synchronize from the client applications. How djradicale does this? Do I have to start a server based on djradicale?

Also I noticed the models on djradicale, I'd like to know if djradicale allows me to store calendar events on tables in a database, I need to do is on a job I'm working on.

Thanks in advance.

**Comment by kyokenn** [comment]
You can set your Radicale-related settings inside of Django configuration file - settings.py.
The storage backend is "djradicale.storage.django" by default, which uses Django ORM. It allows you to store your data in any Django-supported database.

**Comment by Ethan920713** [comment]
I found those settings you mentioned above. I created a new user and when accessing the address localhost:8000/pim with the new user and password I get a blank page. What I still don't understand is how djradicale works with radicale. From your models I can tell the information I'll be saving on my database, also those models remind me the models of django-scheduler, which is good because is what I need for my job. I also created some collections, items and properties on the admin interface with my superuser. But how can I create a new calendar event using djradicale? Do I need an extra configuration? Do I have to run radicale and then djradicale catches the information I'm sending from the client to the server, and save it in its models? That is what I need to know, thanks in advance.

**Comment by kyokenn** [comment]
You don't need to run a separate Radicale server. Radicale should be installed with DjRadicale as dependency, because it's used as a library.
There is no web UI at /pim/, it's a CalDAV/CardDAV endpoint for using with CalDAV/CardDAV client.
